# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MNT
                                 A QGIS plugin
 This plugin creates contour shapefiles based on user-defined zones
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-07
        copyright            : (C) 2025 by Truong Anh Huy LE
        email                : huymop.lee@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MNT class from file MNT.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MNT import MNT
    return MNT(iface)
